server:
  port: 8000

spring:
  application:
    name: service-order
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
  config:
    import: nacos:service-order.properties

logging:
  level:
    com.xiu.feign: debug